### ISSUE TITLE
stop sliding for particular direction

### ISSUE THREAD

**Issue by gibbsvjy007** [letsar/flutter_slidable#136]
As a user I want to only swipe left to right. Nothing should happen when I try to swip from right to left.
Is it possible with this plugin now?

**Comment by TheOnlyNurse** [comment]
I'm interested in this as well. My use case being that my Slidables currently prevent PageView from navigating since it registers the "action icons" drag event despite no "action icons" being supplied.

My two cents on a solution is that there could be mainAxisDirection which specifies the allowed swipe direction regardless of icons present.

**Comment by AcmeField** [comment]
> I'm interested in this as well. My use case being that my Slidables currently prevent PageView from navigating since it registers the "action icons" drag event despite no "action icons" being supplied.
> 
> My two cents on a solution is that there could be mainAxisDirection which specifies the allowed swipe direction regardless of icons present.

Excuse me, Sir. Could you please provide some simple sample code

**Comment by letsar** [comment]
We should mix two views with the same scroll direction.

**Comment by LiangLuDev** [comment]
![image](https://user-images.githubusercontent.com/16227011/102346584-0be66100-3fda-11eb-97e6-678262db6e40.png)
Desired effect：Sliding left pageview responds, sliding right Slidable responds
