### ISSUE TITLE
how about top to bottom or from bottom to top

### ISSUE THREAD

**Issue by MahdiPishguy** [letsar/flutter_slidable#88]
currently version of the library can support swipe right to left or left to right. 
how about top to bottom or from bottom to top

**Comment by anthonysette** [comment]
This is just a guess but may work out for you. I have been parsing the code trying to figure out how to dismiss on tap and see that the slidable.builder() has an attribute of direction which is `this.direction = Axis.horizontal,` by default. If you use slidable.builder() instead of slidable() you should be able to specify that `this.direction = Axis.vertical,`. Again I did not test this but may do the job for you! Hopefully, this helps or points you in the right direction!

**Comment by anthonysette** [comment]
#2 It has been done as seen here. So if what I said is wrong this should help!

**Comment by MahdiPishguy** [comment]
@anthonysette your introduced issue is what i said ,
can we have this feature now?

thanks

**Comment by letsar** [comment]
You can indeed slide vertically. Look at the man current example and change the screen orientation.
